WannaBreak/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Drawing;
using WannaBreak.Data;
using WannaBreak.Models;

namespace WannaBreak.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly WannaBreakContext context;
        public EmployeeController(WannaBreakContext context)
        {
            this.context = context;
        }
        public async Task<IActionResult> Index()
        {
           // display navigation to DisplayEmployees and AddEmployee in "Index-View
            return View();
        }

        public async Task<IActionResult> DisplayEmployees()
        {
            return View(await context.Employees.ToListAsync());
        }

        public async Task<IActionResult> AddEmployee()
        {
            return View(await context.Employees.ToListAsync());
        }

        public async Task<IActionResult> AddNewEmployeeToDB(string firstname, string lastname, string phone, string email, string role, string password)
        {
            firstname = firstname.Trim();
            lastname = lastname.Trim(); 
            phone = phone.Trim();
            email = email.Trim();
            role = role.Trim();
            password = password.Trim();

            Employee employee = new Employee()
            {
                FirstName = firstname = char.ToUpper(firstname[0]) + firstname.Substring(1),
                LastName = lastname = char.ToUpper(lastname[0]) + lastname.Substring(1),
                Phone = phone,
                Email = email,
                Role = role,
                Password = password
            };         
                   
                context.Employees.Add(employee);
                context.SaveChanges();
                return View("AddEmployeeResult");            
        }     
    }
}

WannaBreak/Controllers/VacancyListController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Controller;
using WannaBreak.Data;
using Microsoft.Extensions.Logging;
using WannaBreak.Models;
using System.Data;
using Microsoft.CodeAnalysis.Elfie.Extensions;

namespace WannaBreak.Controllers
{
    public class VacancyListController : Controller
    {
        private readonly WannaBreakContext context;

        public VacancyListController(WannaBreakContext context)
        {
            this.context = context;
        }

        public async Task<IActionResult> Index()
        {
            var newVacancyList = await context.VacancyLists.ToListAsync();
                                

            foreach (var vacancyList in newVacancyList)    // creates list, changing foreign and primary keys to their name insted of key-number
            {
                var employee = await context.Employees
                    .FirstOrDefaultAsync(e => e.EmployeeID == vacancyList.FK_EmployeeID);
                if(employee != null)
                {
                    vacancyList.EmployeeFullName = employee.FirstName + " " + employee.LastName;
                    
                }

                var types = await context.VacancyTypes
                    .FirstOrDefaultAsync(t => t.VacancyTypeID == vacancyList.FK_VacancyTypeID);

                if (types != null)
                {
                    vacancyList.VacancyNameTitel = types.VacancyTitel;

                }
            }                 
            return View(newVacancyList);
        }

        // Navigation in VacancyListStartPage
        public async Task<IActionResult> SearchName()
        {
            return View();
        }

        public async Task<IActionResult> GetSearchNameInput(string employeeFirstname, string employeeLastname)
        {
            bool nameFound = false;
            int getId = 0;

            employeeFirstname = employeeFirstname.Trim();
            employeeLastname = employeeLastname.Trim();

            var newEmployeeList = await context.Employees.ToListAsync();

            foreach (var employee in newEmployeeList)
            {
                if (employeeFirstname.ToLower() == employee.FirstName.ToLower() && employeeLastname.ToLower() == employee.LastName.ToLower())
                {
                        getId = employee.EmployeeID;
                        nameFound = true;
                        break;
                }
            }

            if (nameFound) // changing fk-int key to matching vacancytypes-names
            {
                var newVacancyList = await context.VacancyLists
                    .Where( v => v.FK_EmployeeID == getId )
                    .ToListAsync();

                foreach (var vacancyList in newVacancyList)
                {

                    var vacancyTypes = await context.VacancyTypes
                        .FirstOrDefaultAsync(v => v.VacancyTypeID == vacancyList.FK_VacancyTypeID);

                    if(vacancyTypes != null)
                    {
                        vacancyList.VacancyNameTitel = vacancyTypes.VacancyTitel;
                    }
                }

                return View("searchNameResult", newVacancyList);
            }
            else
            {
                return View("NoMatch");
            }
        }

        // Navigation in VacancyListStartPage - Index
        public async Task<IActionResult> DateSearch()
        {
            return View();
        }

        //GetSearchDateInput
        public async Task<IActionResult> GetSearchDateInput(DateTime startDate, DateTime stopDate)
        {
            var newVacancyList = await context.VacancyLists
                .Where(v => v.Start >= startDate && v.Stop <= stopDate)
                .ToListAsync();

            foreach (var vacancyList in newVacancyList)
            {
                var vacancyTypes = await context.VacancyTypes
                    .FirstOrDefaultAsync(v => v.VacancyTypeID == vacancyList.FK_VacancyTypeID);        

                if (vacancyTypes != null )
                {
                    vacancyList.VacancyNameTitel = vacancyTypes.VacancyTitel;
                }

                
                var employee = await context.Employees
                    
                    .FirstOrDefaultAsync(e => e.EmployeeID == vacancyList.FK_EmployeeID);
                if (employee != null)
                {
                    vacancyList.EmployeeFullName = employee.FirstName + " " + employee.LastName;
                }
            }
            return View("searchDateResult", newVacancyList);
        }

        public async Task<IActionResult> AddVacancy()
        {
                return View();
        }

        //POST
        public async Task<IActionResult> AddVacancyListToDB(int fkEmployeeId, string fkVacancyType, DateTime start, DateTime stop)
        {
            int vacancyType = 1;

            foreach (var item in context.VacancyTypes)
            {
                if(item.VacancyTitel.ToLower() == fkVacancyType.ToLower())
                {
                    vacancyType = item.VacancyTypeID;
                    break;
                }
            }

            VacancyList vacancyList = new VacancyList()
            {
                FK_EmployeeID = fkEmployeeId,
                FK_VacancyTypeID = vacancyType,
                Start = start,
                Stop = stop,
                RegisteredDate = DateTime.Now
            };
            context.VacancyLists.Add(vacancyList);
            context.SaveChanges();

            return View();
        }
    }
}

WannaBreak/Controllers/VacancyTypeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WannaBreak.Data;

namespace WannaBreak.Controllers
{    
    public class VacancyTypeController : Controller
    {
        private readonly WannaBreakContext context;
        public VacancyTypeController(WannaBreakContext context)
        {
            this.context = context;
        }
        public async Task<IActionResult> Index()
        {
            return View(await context.VacancyTypes.ToListAsync());         
        }
    }
}

WannaBreak/Views/Shared/NoMatch.cshtml
@{
    ViewData["Title"] = "NoMatch";
}

<h1>No match for That!</h1>

WannaBreak/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WannaBreak</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WannaBreak.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WannaBreak</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employees</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="VacancyList" asp-action="Index">Break Lists!</a>
                        </li>

                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="VacancyType" asp-action="Index">Break Types!</a>
                        </li>                      

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Admin and Bosses</a>
                        </li>                      
         
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WannaBreak - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>